%YAML:1.0
aruco_bc_nmarkers: 12
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:205, corners:[ [ -300., -200., 0. ], [ -200., -200., 0. ], [
       -200., -100., 0. ], [ -300., -100., 0. ] ] }
   - { id:198, corners:[ [ -100., -200., 0. ], [ 0., -200., 0. ], [ 0.,
       -100., 0. ], [ -100., -100., 0. ] ] }
   - { id:610, corners:[ [ 100., -200., 0. ], [ 200., -200., 0. ], [
       200., -100., 0. ], [ 100., -100., 0. ] ] }
   - { id:242, corners:[ [ -200., -100., 0. ], [ -100., -100., 0. ], [
       -100., 0., 0. ], [ -200., 0., 0. ] ] }
   - { id:631, corners:[ [ 0., -100., 0. ], [ 100., -100., 0. ], [ 100.,
       0., 0. ], [ 0., 0., 0. ] ] }
   - { id:43, corners:[ [ 200., -100., 0. ], [ 300., -100., 0. ], [ 300.,
       0., 0. ], [ 200., 0., 0. ] ] }
   - { id:226, corners:[ [ -300., 0., 0. ], [ -200., 0., 0. ], [ -200.,
       100., 0. ], [ -300., 100., 0. ] ] }
   - { id:724, corners:[ [ -100., 0., 0. ], [ 0., 0., 0. ], [ 0., 100.,
       0. ], [ -100., 100., 0. ] ] }
   - { id:20, corners:[ [ 100., 0., 0. ], [ 200., 0., 0. ], [ 200., 100.,
       0. ], [ 100., 100., 0. ] ] }
   - { id:658, corners:[ [ -200., 100., 0. ], [ -100., 100., 0. ], [
       -100., 200., 0. ], [ -200., 200., 0. ] ] }
   - { id:938, corners:[ [ 0., 100., 0. ], [ 100., 100., 0. ], [ 100.,
       200., 0. ], [ 0., 200., 0. ] ] }
   - { id:445, corners:[ [ 200., 100., 0. ], [ 300., 100., 0. ], [ 300.,
       200., 0. ], [ 200., 200., 0. ] ] }
