%YAML:1.0
aruco_bc_nmarkers: 24
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:320, corners:[ [ -350., -230., 0. ], [ -250., -230., 0. ], [
       -250., -130., 0. ], [ -350., -130., 0. ] ] }
   - { id:123, corners:[ [ -230., -230., 0. ], [ -130., -230., 0. ], [
       -130., -130., 0. ], [ -230., -130., 0. ] ] }
   - { id:209, corners:[ [ -110., -230., 0. ], [ -10., -230., 0. ], [
       -10., -130., 0. ], [ -110., -130., 0. ] ] }
   - { id:429, corners:[ [ 10., -230., 0. ], [ 110., -230., 0. ], [ 110.,
       -130., 0. ], [ 10., -130., 0. ] ] }
   - { id:905, corners:[ [ 130., -230., 0. ], [ 230., -230., 0. ], [
       230., -130., 0. ], [ 130., -130., 0. ] ] }
   - { id:225, corners:[ [ 250., -230., 0. ], [ 350., -230., 0. ], [
       350., -130., 0. ], [ 250., -130., 0. ] ] }
   - { id:75, corners:[ [ -350., -110., 0. ], [ -250., -110., 0. ], [
       -250., -10., 0. ], [ -350., -10., 0. ] ] }
   - { id:224, corners:[ [ -230., -110., 0. ], [ -130., -110., 0. ], [
       -130., -10., 0. ], [ -230., -10., 0. ] ] }
   - { id:608, corners:[ [ -110., -110., 0. ], [ -10., -110., 0. ], [
       -10., -10., 0. ], [ -110., -10., 0. ] ] }
   - { id:89, corners:[ [ 10., -110., 0. ], [ 110., -110., 0. ], [ 110.,
       -10., 0. ], [ 10., -10., 0. ] ] }
   - { id:335, corners:[ [ 130., -110., 0. ], [ 230., -110., 0. ], [
       230., -10., 0. ], [ 130., -10., 0. ] ] }
   - { id:677, corners:[ [ 250., -110., 0. ], [ 350., -110., 0. ], [
       350., -10., 0. ], [ 250., -10., 0. ] ] }
   - { id:659, corners:[ [ -350., 10., 0. ], [ -250., 10., 0. ], [ -250.,
       110., 0. ], [ -350., 110., 0. ] ] }
   - { id:462, corners:[ [ -230., 10., 0. ], [ -130., 10., 0. ], [ -130.,
       110., 0. ], [ -230., 110., 0. ] ] }
   - { id:1007, corners:[ [ -110., 10., 0. ], [ -10., 10., 0. ], [ -10.,
       110., 0. ], [ -110., 110., 0. ] ] }
   - { id:567, corners:[ [ 10., 10., 0. ], [ 110., 10., 0. ], [ 110.,
       110., 0. ], [ 10., 110., 0. ] ] }
   - { id:983, corners:[ [ 130., 10., 0. ], [ 230., 10., 0. ], [ 230.,
       110., 0. ], [ 130., 110., 0. ] ] }
   - { id:539, corners:[ [ 250., 10., 0. ], [ 350., 10., 0. ], [ 350.,
       110., 0. ], [ 250., 110., 0. ] ] }
   - { id:748, corners:[ [ -350., 130., 0. ], [ -250., 130., 0. ], [
       -250., 230., 0. ], [ -350., 230., 0. ] ] }
   - { id:505, corners:[ [ -230., 130., 0. ], [ -130., 130., 0. ], [
       -130., 230., 0. ], [ -230., 230., 0. ] ] }
   - { id:273, corners:[ [ -110., 130., 0. ], [ -10., 130., 0. ], [ -10.,
       230., 0. ], [ -110., 230., 0. ] ] }
   - { id:182, corners:[ [ 10., 130., 0. ], [ 110., 130., 0. ], [ 110.,
       230., 0. ], [ 10., 230., 0. ] ] }
   - { id:536, corners:[ [ 130., 130., 0. ], [ 230., 130., 0. ], [ 230.,
       230., 0. ], [ 130., 230., 0. ] ] }
   - { id:767, corners:[ [ 250., 130., 0. ], [ 350., 130., 0. ], [ 350.,
       230., 0. ], [ 250., 230., 0. ] ] }
